#!/bin/bash
cutflow isMC 4topSM
cutflow isMC Zee
cutflow isMC Zmumu
cutflow isMC ttbar
cutflow isMC Wplusenu
cutflow isMC Wplusmunu
cutflow isMC Wplustaunu
cutflow isMC Wminusenu
cutflow isMC Wminusmunu
cutflow isMC Wminustaunu
cutflow isMC Ztautau
cutflow isMC ttW_Np0
cutflow isMC ttW_Np1
cutflow isMC ttW_Np2
cutflow isMC ttee_Np0
cutflow isMC ttee_Np1
cutflow isMC ttmumu_Np0
cutflow isMC ttmumu_Np1
cutflow isMC tttautau_Np0
cutflow isMC tttautau_Np1
cutflow isMC ttbarWW
cutflow isMC 3top_SM
cutflow isMC llll
cutflow isMC lllvSFMinus
cutflow isMC lllvOFMinus
cutflow isMC lllvSFPlus
cutflow isMC lllvOFPlus
cutflow isMC llvvjj_ss_EW4
cutflow isMC llvvjj_ss_EW6
cutflow isMC llvvjj_EW6
cutflow isMC lllljj_EW6
cutflow isMC ggllll
cutflow isMC ZZZ_6l0v
cutflow isMC ZZZ_4l2v
cutflow isMC ZZZ_2l4v
cutflow isMC llvv
cutflow isMC ggllvv
cutflow isMC WqqZll
cutflow isMC ZqqZll
cutflow isMC singletop_tchan_lept_top
cutflow isMC singletop_tchan_lept_antitop
cutflow isMC Wt_inclusive_top
cutflow isMC Wt_inclusive_antitop
cutflow isMC Wt_dilepton_top
cutflow isMC Wt_dilepton_antitop
cutflow isMC ttbarHT6c_1k_hdamp172p5
cutflow isMC ttbarHT1k_1k5_hdamp172p5
cutflow isMC ttbarHT1k5_hdamp172p5_no
